### ISSUE TITLE
line chart doesn't plot .

### ISSUE THREAD

**Issue by kanatronics** [adafruit/io-issues#105]
One of my line charts  stopped plotting data. The data is streamed continuously to feed and is present on the chart as a point. Any possible solution to fix this problem?

Thanks Kamil 

![plot1](https://cloud.githubusercontent.com/assets/12275576/12418175/7c0daa94-bea5-11e5-8f60-389c0897e739.png)

**Comment by toddtreece** [comment]
@kanatronics could you give it another shot? the issue should be fixed

**Comment by kanatronics** [comment]
Unfortunately the same line charts still isn’t plotting data.  Please see attached two current plots.
Thanks,


![plot2](https://cloud.githubusercontent.com/assets/12275576/12420237/57b8c88c-beb3-11e5-8c25-736361450c1a.png)
![plot3](https://cloud.githubusercontent.com/assets/12275576/12420242/5ccb6ece-beb3-11e5-8b6b-34bda6e52374.png)

**Comment by toddtreece** [comment]
@kanatronics can you check if your feed is getting data here: https://io.adafruit.com/feeds

**Comment by kanatronics** [comment]
Yes the feed is getting data.

![plot](https://cloud.githubusercontent.com/assets/12275576/12422185/9b6eb82a-bebd-11e5-9eb4-22326248d945.png)

**Comment by toddtreece** [comment]
@kanatronics now that we know you are getting data, could you load the dashboard again and open the javascript console in chrome? if there are any errors, could you paste them in?

<img width="577" alt="screen shot 2016-01-19 at 10 07 33 am" src="https://cloud.githubusercontent.com/assets/360020/12422339/7e1933f0-be94-11e5-85b9-05cd389a6201.png">

thanks for the help investigating this issue!

**Comment by kanatronics** [comment]
Hi Todd

6 errors were found.  Please see below attached code.

Thanks,



application-0ab5a9c7f17d388030fe2dd129eb41499f3c1fff17db3a772d70c34107f91b6b.js:82 Error: Invalid value for <svg> attribute height="NaN"


/ NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
var I=/%[sdj%]/g;n.format=function(t){if(!y(t)){for(var e=[],n=0;n<arguments.length;n++)e.push(r(arguments[n]));return e.join(" ")}for(var n=1,i=arguments,o=i.length,s=String(t).replace(I,function(t){if("%%"===t)return"%";if(n>=o)return t;switch(t){case"%s":return String(i[n++]);case"%d":return Number(i[n++]);case"%j":try{return JSON.stringify(i[n++])}c



 
![error](https://cloud.githubusercontent.com/assets/12275576/12423913/9f25f00c-bec5-11e5-8a6f-3075a6ee0143.png)

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
